services:

    # Doctrine DBAL
    # --------------------------------------------------------------------------

    doctrine.dbal_connection:
        class: Doctrine\DBAL\Connection
        factory: ['Doctrine\DBAL\DriverManager', getConnection]
        arguments:
            -
                url: "%env(DATABASE_DSN)%"
                driver: 'pdo_pgsql'

    doctrine.dbal_schema.definition:
        class: Infrastructure\Persistence\Doctrine\SchemaDefinition

    doctrine.dbal_schema.base_command:
        class: DbalSchema\DbalSchemaCommand
        arguments:
            - '@doctrine.dbal_connection'
            - '@doctrine.dbal_schema.definition'

    doctrine.dbal_schema.command.update_command:
        class: DbalSchema\Command\UpdateCommand
        arguments: ['@doctrine.dbal_schema.base_command']
        tags: [ { name: console.command } ]
    doctrine.dbal_schema.command.purge_command:
        class: DbalSchema\Command\PurgeCommand
        arguments: ['@doctrine.dbal_schema.base_command']
        tags: [ { name: console.command } ]

    # Cities
    # --------------------------------------------------------------------------

    app.city_repository:
        class: Infrastructure\Persistence\InMemory\InMemoryCityRepository
        factory: ['Infrastructure\Persistence\InMemory\InMemoryCityRepositoryFactory', create]
        arguments: ['%app.techmeetups.cities%']

    app.city_configuration_repository:
        class: Infrastructure\Persistence\InMemory\InMemoryCityConfigurationRepository
        factory: ['Infrastructure\Persistence\InMemory\InMemoryCityConfigurationRepositoryFactory', create]
        arguments:
            - '@app.city_repository'
            - '%app.techmeetups.cities%'

    # Events
    # --------------------------------------------------------------------------

    app.event_repository:
        class: Infrastructure\Persistence\Doctrine\DbalEventRepository
        arguments: ['@doctrine.dbal_connection']

    app.event_finder:
        class: Infrastructure\ReadModel\Doctrine\DbalEventFinder
        arguments: ['@doctrine.dbal_connection']

    app.meetup_client:
        class: Meetup\Meetup
        factory: ['Meetup\MeetupApiKeyFactory', create]
        arguments: ['%env(MEETUP_API_KEY)%', '@logger']

    app.event_provider.meetup:
        class: Infrastructure\Api\Meetup\EventProvider
        arguments: ['@app.meetup_client']

    app.base_event_manager:
        abstract:  true
        arguments:
            - '@app.city_configuration_repository'
            - '@app.event_provider.meetup'
            - '@app.event_repository'
            - '@logger'

    app.event_importer:
        class: Application\EventImporter
        parent: app.base_event_manager

    app.event_synchronizer:
        class: Application\EventSynchronizer
        parent: app.base_event_manager

    app.command.event_importer:
        class: Infrastructure\Cli\ImporterCommand
        arguments: ['@app.event_importer']
        tags:
            - { name: console.command }

    app.command.event_synchronizer:
        class: Infrastructure\Cli\SynchronizerCommand
        arguments: ['@app.event_synchronizer']
        tags:
            - { name: console.command }

    # Actions
    # --------------------------------------------------------------------------
    app.actions.homepage:
        class: UI\Action\Homepage
        arguments: ['@app.event_finder', '@twig']

    app.actions.feed:
        class: UI\Action\Feed
        arguments: ['@app.event_finder']

    app.actions.ical:
        class: UI\Action\ICal
        arguments: ['@app.event_finder']

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
